name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    container: gitguardian/ggshield:latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: rsmnarts/pg_activity

      - name: Scan image with ggshield
        run: |
          ggshield scan docker rsmnarts/pg_activity:${{ github.sha }}
